# Generated by Django 4.2.2 on 2023-06-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('ci', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('fone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=50)),
                ('anio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante_Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estudiante', to='notas.estudiante')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gestiones', to='notas.gestion')),
            ],
        ),
    ]
