# Generated by Django 4.2.2 on 2023-06-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
    ]
